name: 2nd-workflow

on:
  push:
    branches:
      - main
    paths:
      - "dir-1/**"

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: linux commands
        run: |
           ls -a
           pwd
           whoami
           echo "finished"